a = do(pd.read_csv)(filenames[0])
b = do(pd.read_csv)(filenames[1])
c = do(pd.read_csv)(filenames[2])
na = delayed(len)(a)
nb = delayed(len)(b)
nc = delayed(len)(c)
total = delayed(sum)([na, nb, nc])
