#!/bin/bash

# Install the JupyterLab dask-labextension
# TODO: Unpin dask-labextension version once extensions have been made compatibility updates
jupyter labextension install dask-labextension@1.1.0
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @bokeh/jupyter_bokeh
