#!/bin/bash

# Install the JupyterLab dask-labextension
jupyter labextension install dask-labextension

# Install ipywidgets for displaying the cluster widget
jupyter labextension install @jupyter-widgets/jupyterlab-manager
