#!/bin/bash

# Replace DASK_DASHBOARD_URL with the proxy location
sed -i -e "s|DASK_DASHBOARD_URL|/user/${JUPYTERHUB_USER}/proxy/8787|g" binder/jupyterlab-workspace.json

# Import the workspace
jupyter lab workspaces import binder/jupyterlab-workspace.json
export DASK_TUTORIAL_SMALL=1

exec "$@"
